name: Release

permissions:
  contents: write

on:
  release:
    types: [prereleased, released]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: filesharing
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
          include: compose.yaml,Dockerfile,.env.example,assets,LICENSE.md
